CREATE TABLE IF NOT EXISTS public."FactSales"
(
    "salesId" integer NOT NULL,
    quantity bigint NOT NULL,
    amount double precision NOT NULL,
    "productId" integer NOT NULL,
    "customerId" integer NOT NULL,
    "monthId" integer NOT NULL,
    invoicedate timestamp without time zone NOT NULL,
    "invoiceNo" character varying(7) COLLATE pg_catalog."default",
    CONSTRAINT "FactSales_pkey" PRIMARY KEY ("salesId"),
    CONSTRAINT "FactSales_customerId_fkey" FOREIGN KEY ("customerId")
    REFERENCES public."DimCustomer" ("customerId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT "FactSales_monthId_fkey" FOREIGN KEY ("monthId")
    REFERENCES public."DimMonth" ("monthId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT "FactSales_stockId_fkey" FOREIGN KEY ("productId")
    REFERENCES public."DimProduct" ("productId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE,
)
PARTITION BY RANGE ("invoicedate");


CREATE TABLE DimMonth_2010 PARTITION OF "DimMonth"
FOR VALUES FROM (2010) TO (2011);


CREATE TABLE DimMonth_2011 PARTITION OF "DimMonth"
FOR VALUES FROM (2011) TO (2012);

CREATE TABLE DimMonth_2012 PARTITION OF "DimMonth"
FOR VALUES FROM (2012) TO (2013);

CREATE TABLE DimMonth_2013 PARTITION OF "DimMonth"
FOR VALUES FROM (2013) TO (2014);

CREATE TABLE DimMonth_2014 PARTITION OF "DimMonth"
FOR VALUES FROM (2014) TO (2015);

CREATE TABLE DimMonth_2015 PARTITION OF "DimMonth"
FOR VALUES FROM (2015) TO (2016);

CREATE TABLE DimMonth_2016 PARTITION OF "DimMonth"
FOR VALUES FROM (2016) TO (2017);

CREATE TABLE DimMonth_2017 PARTITION OF "DimMonth"
FOR VALUES FROM (2017) TO (2018);

CREATE TABLE DimMonth_2018 PARTITION OF "DimMonth"
FOR VALUES FROM (2018) TO (2019);

CREATE TABLE DimMonth_2019 PARTITION OF "DimMonth"
FOR VALUES FROM (2019) TO (2020);

CREATE TABLE DimMonth_2020 PARTITION OF "DimMonth"
FOR VALUES FROM (2020) TO (2021);

CREATE TABLE DimMonth_2021 PARTITION OF "DimMonth"
FOR VALUES FROM (2021) TO (2022);

CREATE TABLE DimMonth_2022 PARTITION OF "DimMonth"
FOR VALUES FROM (2022) TO (2023);

CREATE TABLE DimMonth_2023 PARTITION OF "DimMonth"
FOR VALUES FROM (2023) TO (2024);

CREATE TABLE DimMonth_2024 PARTITION OF "DimMonth"
FOR VALUES FROM (2024) TO (2025);
